const ROOM_TYPES_MOCK = [
  {
    _id: 'rt1',
    name: 'Deluxe Forest View',
    area: 35,
    price_per_night: 120,
    bed_options: ['1 double bed', '2 single beds'],
    capacity: { adults: 2, children: 2 },
    description: 'Double room with pool view and private bathroom',
    amenities: ['WiFi', 'Air conditioning', 'Minibar'],
    rate_includes: ['Breakfast', 'Free WiFi'],
    service_charge: 5,
    vat: true,
  },
  {
    _id: 'rt2',
    name: 'Premium Ocean View',
    area: 42,
    price_per_night: 220,
    bed_options: ['1 king bed'],
    capacity: { adults: 2, children: 1 },
    description: 'Ocean-facing room with balcony and rainfall shower',
    amenities: ['WiFi', 'Air conditioning', 'Bathtub', 'Smart TV'],
    rate_includes: ['Breakfast', 'Welcome drink'],
    service_charge: 5,
    vat: true,
  },
  {
    _id: 'rt3',
    name: 'Family Garden Suite',
    area: 55,
    price_per_night: 320,
    bed_options: ['1 queen bed', '2 single beds'],
    capacity: { adults: 4, children: 2 },
    description: 'Spacious suite suitable for family stays',
    amenities: ['WiFi', 'Kitchenette', 'Living area', 'Minibar'],
    rate_includes: ['Breakfast', 'Afternoon tea'],
    service_charge: 5,
    vat: true,
  },
  {
    _id: 'rt4',
    name: 'Executive Business Room',
    area: 32,
    price_per_night: 150,
    bed_options: ['1 queen bed'],
    capacity: { adults: 2, children: 0 },
    description: 'Business room with dedicated workspace',
    amenities: ['WiFi', 'Work desk', 'Coffee machine'],
    rate_includes: ['Breakfast', 'Laundry discount'],
    service_charge: 5,
    vat: true,
  },
];

const ROOMS_MOCK = [
  {
    _id: 'r1',
    room_number: '301',
    room_type_id: 'rt1',
    floor: 3,
    status: 'available',
    beach_view: true,
    is_active: true,
  },
  {
    _id: 'r2',
    room_number: '302',
    room_type_id: 'rt1',
    floor: 3,
    status: 'occupied',
    beach_view: false,
    is_active: true,
  },
  {
    _id: 'r3',
    room_number: '303',
    room_type_id: 'rt1',
    floor: 3,
    status: 'maintenance',
    beach_view: false,
    is_active: false,
  },
  {
    _id: 'r4',
    room_number: '304',
    room_type_id: 'rt2',
    floor: 3,
    status: 'available',
    beach_view: true,
    is_active: true,
  },
  {
    _id: 'r5',
    room_number: '305',
    room_type_id: 'rt4',
    floor: 3,
    status: 'occupied',
    beach_view: false,
    is_active: true,
  },
  {
    _id: 'r6',
    room_number: '401',
    room_type_id: 'rt2',
    floor: 4,
    status: 'maintenance',
    beach_view: true,
    is_active: true,
  },
  {
    _id: 'r7',
    room_number: '402',
    room_type_id: 'rt2',
    floor: 4,
    status: 'available',
    beach_view: true,
    is_active: true,
  },
  {
    _id: 'r8',
    room_number: '403',
    room_type_id: 'rt3',
    floor: 4,
    status: 'occupied',
    beach_view: false,
    is_active: true,
  },
  {
    _id: 'r9',
    room_number: '404',
    room_type_id: 'rt3',
    floor: 4,
    status: 'available',
    beach_view: false,
    is_active: true,
  },
  {
    _id: 'r10',
    room_number: '501',
    room_type_id: 'rt4',
    floor: 5,
    status: 'occupied',
    beach_view: false,
    is_active: true,
  },
  {
    _id: 'r11',
    room_number: '502',
    room_type_id: 'rt4',
    floor: 5,
    status: 'available',
    beach_view: true,
    is_active: true,
  },
  {
    _id: 'r12',
    room_number: '503',
    room_type_id: 'rt3',
    floor: 5,
    status: 'maintenance',
    beach_view: false,
    is_active: false,
  },
  {
    _id: 'r13',
    room_number: '504',
    room_type_id: 'rt1',
    floor: 5,
    status: 'available',
    beach_view: true,
    is_active: true,
  },
];

module.exports = {
  ROOM_TYPES_MOCK,
  ROOMS_MOCK,
};
